export type SimuleToolCategory = 'map' | 'sensor' | 'policy' | 'response' | 'recovery' | 'special';

export interface SimuleTool {
  id: string;
  gameId: string;
  battleId: number;
  name: string;
  category: SimuleToolCategory;
  battleCategory: 'recon' | 'network' | 'web' | 'crypto' | 'malware' | 'social' | 'defense' | 'advanced';
  icon: string;
  training: string;
  strength: string;
  blindSpot: string;
  energy: number;
  power: number;
  tier: number;
  stealthLevel: number;
  cooldown: number;
  defenseBreak: number;
  unlockLevel: number;
}

export const SIMULE_TOOL_CATEGORY_LABELS: Record<SimuleToolCategory, string> = {
  map: 'Map',
  sensor: 'Sensor',
  policy: 'Policy',
  response: 'Response',
  recovery: 'Recovery',
  special: 'Special',
};

export const SIMULE_TOOL_CATEGORY_COLORS: Record<SimuleToolCategory, string> = {
  map: '#A78BFA',
  sensor: '#60A5FA',
  policy: '#FACC15',
  response: '#F87171',
  recovery: '#4ADE80',
  special: '#F472B6',
};

export const SIMULE_TOOLS: SimuleTool[] = [
  {
    id: 'password-quest',
    gameId: 'password-quest',
    battleId: 1,
    name: 'Password Quest',
    category: 'policy',
    battleCategory: 'crypto',
    icon: 'Lock',
    training: 'Password Hygiene',
    strength: 'Hardens accounts with strong secret design and safe reset habits.',
    blindSpot: 'Does not detect live traffic or malware by itself.',
    energy: 4,
    power: 16,
    tier: 1,
    stealthLevel: 2,
    cooldown: 10,
    defenseBreak: 6,
    unlockLevel: 1,
  },
  {
    id: 'phishing-detective',
    gameId: 'phishing-detective',
    battleId: 2,
    name: 'Phishing Detective',
    category: 'sensor',
    battleCategory: 'social',
    icon: 'Mail',
    training: 'Phishing Clues',
    strength: 'Finds suspicious senders, links, wording, and urgency patterns.',
    blindSpot: 'Needs policy or response tools to contain confirmed abuse.',
    energy: 4,
    power: 15,
    tier: 1,
    stealthLevel: 4,
    cooldown: 8,
    defenseBreak: 5,
    unlockLevel: 1,
  },
  {
    id: 'firewall-defender',
    gameId: 'firewall-defender',
    battleId: 3,
    name: 'Firewall Defender',
    category: 'policy',
    battleCategory: 'defense',
    icon: 'Shield',
    training: 'Firewall Rule Order',
    strength: 'Creates narrow allow and block rules while preserving healthy traffic.',
    blindSpot: 'Broad rules can create false-positive damage.',
    energy: 6,
    power: 18,
    tier: 1,
    stealthLevel: 2,
    cooldown: 12,
    defenseBreak: 10,
    unlockLevel: 1,
  },
  {
    id: 'crypto-cat',
    gameId: 'crypto-cat',
    battleId: 4,
    name: 'Crypto Cat',
    category: 'policy',
    battleCategory: 'crypto',
    icon: 'Lock',
    training: 'Encryption Basics',
    strength: 'Protects messages and teaches when encoded data is trustworthy.',
    blindSpot: 'Encryption does not explain traffic spikes or service failures.',
    energy: 5,
    power: 22,
    tier: 1,
    stealthLevel: 3,
    cooldown: 16,
    defenseBreak: 8,
    unlockLevel: 2,
  },
  {
    id: 'malware-hunter',
    gameId: 'malware-hunter',
    battleId: 5,
    name: 'Malware Hunter',
    category: 'response',
    battleCategory: 'malware',
    icon: 'Bug',
    training: 'Malware Response',
    strength: 'Identifies and removes simulated malicious processes quickly.',
    blindSpot: 'Can miss root cause without logs or network evidence.',
    energy: 7,
    power: 26,
    tier: 1,
    stealthLevel: 2,
    cooldown: 18,
    defenseBreak: 12,
    unlockLevel: 2,
  },
  {
    id: 'network-navigator',
    gameId: 'network-navigator',
    battleId: 6,
    name: 'Network Navigator',
    category: 'map',
    battleCategory: 'network',
    icon: 'Wifi',
    training: 'Network Paths',
    strength: 'Shows how packets move through routers, firewalls, and services.',
    blindSpot: 'Topology alone does not prove the active threat.',
    energy: 5,
    power: 20,
    tier: 1,
    stealthLevel: 3,
    cooldown: 14,
    defenseBreak: 7,
    unlockLevel: 2,
  },
  {
    id: 'cyber-duel-arena',
    gameId: 'cyber-duel-arena',
    battleId: 7,
    name: 'Cyber Duel Arena',
    category: 'special',
    battleCategory: 'advanced',
    icon: 'Swords',
    training: 'Evidence-Based Loadout',
    strength: 'Combines map, sensor, policy, response, recovery, and special tools.',
    blindSpot: 'Strong only when paired with a focused mission goal.',
    energy: 9,
    power: 34,
    tier: 2,
    stealthLevel: 3,
    cooldown: 34,
    defenseBreak: 16,
    unlockLevel: 4,
  },
  {
    id: 'ssl-handshake',
    gameId: 'ssl-handshake',
    battleId: 8,
    name: 'SSL Handshake',
    category: 'sensor',
    battleCategory: 'crypto',
    icon: 'Lock',
    training: 'TLS Flow',
    strength: 'Explains certificate exchange and encrypted session setup.',
    blindSpot: 'Does not inspect application-layer behavior.',
    energy: 5,
    power: 24,
    tier: 2,
    stealthLevel: 3,
    cooldown: 20,
    defenseBreak: 10,
    unlockLevel: 3,
  },
  {
    id: 'dns-resolver',
    gameId: 'dns-resolver',
    battleId: 9,
    name: 'DNS Resolver',
    category: 'sensor',
    battleCategory: 'network',
    icon: 'Globe',
    training: 'Resolver Hygiene',
    strength: 'Finds wrong answers, route drift, and resolver mismatches.',
    blindSpot: 'Does not read app logs or fix policy by itself.',
    energy: 5,
    power: 24,
    tier: 2,
    stealthLevel: 4,
    cooldown: 18,
    defenseBreak: 9,
    unlockLevel: 3,
  },
  {
    id: 'packet-tracer',
    gameId: 'packet-tracer',
    battleId: 10,
    name: 'Packet Tracer',
    category: 'map',
    battleCategory: 'network',
    icon: 'Activity',
    training: 'Packet Flow',
    strength: 'Traces where packets slow down, drop, or take unsafe paths.',
    blindSpot: 'Needs sensor detail to classify packet intent.',
    energy: 5,
    power: 26,
    tier: 2,
    stealthLevel: 3,
    cooldown: 20,
    defenseBreak: 10,
    unlockLevel: 4,
  },
  {
    id: 'subnet-calculator',
    gameId: 'subnet-calculator',
    battleId: 11,
    name: 'Subnet Calculator',
    category: 'map',
    battleCategory: 'network',
    icon: 'Network',
    training: 'Subnet Boundaries',
    strength: 'Scopes networks, ranges, and containment zones before action.',
    blindSpot: 'Math does not detect live anomalies alone.',
    energy: 4,
    power: 18,
    tier: 1,
    stealthLevel: 3,
    cooldown: 14,
    defenseBreak: 7,
    unlockLevel: 2,
  },
  {
    id: 'vpn-tunnel',
    gameId: 'vpn-tunnel',
    battleId: 12,
    name: 'VPN Tunnel',
    category: 'policy',
    battleCategory: 'network',
    icon: 'ShieldCheck',
    training: 'Secure Tunneling',
    strength: 'Protects remote access paths and narrows trusted routes.',
    blindSpot: 'A tunnel can still carry bad traffic if identity is weak.',
    energy: 7,
    power: 30,
    tier: 2,
    stealthLevel: 4,
    cooldown: 28,
    defenseBreak: 13,
    unlockLevel: 5,
  },
  {
    id: 'load-balancer',
    gameId: 'load-balancer',
    battleId: 13,
    name: 'Load Balancer',
    category: 'recovery',
    battleCategory: 'defense',
    icon: 'Shuffle',
    training: 'Traffic Distribution',
    strength: 'Keeps service responsive by shifting pressure across healthy nodes.',
    blindSpot: 'Can spread a problem if the root cause is unknown.',
    energy: 8,
    power: 32,
    tier: 2,
    stealthLevel: 2,
    cooldown: 30,
    defenseBreak: 14,
    unlockLevel: 5,
  },
  {
    id: 'ids-alert',
    gameId: 'ids-alert',
    battleId: 14,
    name: 'IDS Alert',
    category: 'sensor',
    battleCategory: 'defense',
    icon: 'Eye',
    training: 'Alert Triage',
    strength: 'Separates signal from noise and highlights suspicious activity.',
    blindSpot: 'Alerts need context before blocking decisions.',
    energy: 6,
    power: 28,
    tier: 2,
    stealthLevel: 4,
    cooldown: 24,
    defenseBreak: 12,
    unlockLevel: 4,
  },
  {
    id: 'certificate-chain',
    gameId: 'certificate-chain',
    battleId: 15,
    name: 'Certificate Chain',
    category: 'sensor',
    battleCategory: 'crypto',
    icon: 'Lock',
    training: 'Trust Chain',
    strength: 'Validates issuer paths and broken trust relationships.',
    blindSpot: 'Cannot inspect endpoint behavior after trust is valid.',
    energy: 5,
    power: 27,
    tier: 2,
    stealthLevel: 3,
    cooldown: 22,
    defenseBreak: 11,
    unlockLevel: 4,
  },
  {
    id: 'proxy-server',
    gameId: 'proxy-server',
    battleId: 16,
    name: 'Proxy Server',
    category: 'policy',
    battleCategory: 'network',
    icon: 'Globe',
    training: 'Proxy Routing',
    strength: 'Controls request paths and shields backend services.',
    blindSpot: 'Misrouting can hide the real user impact.',
    energy: 7,
    power: 31,
    tier: 2,
    stealthLevel: 4,
    cooldown: 30,
    defenseBreak: 14,
    unlockLevel: 5,
  },
  {
    id: 'port-scanner',
    gameId: 'port-scanner',
    battleId: 17,
    name: 'Port Scanner',
    category: 'sensor',
    battleCategory: 'recon',
    icon: 'Search',
    training: 'Service Discovery',
    strength: 'Finds exposed services and likely entry points.',
    blindSpot: 'Discovery does not equal exploitation or remediation.',
    energy: 5,
    power: 29,
    tier: 2,
    stealthLevel: 2,
    cooldown: 20,
    defenseBreak: 12,
    unlockLevel: 3,
  },
  {
    id: 'encryption-pipeline',
    gameId: 'encryption-pipeline',
    battleId: 18,
    name: 'Encryption Pipeline',
    category: 'policy',
    battleCategory: 'crypto',
    icon: 'Lock',
    training: 'Data Protection',
    strength: 'Protects data through staged encode, encrypt, and verify steps.',
    blindSpot: 'Does not classify whether traffic is healthy.',
    energy: 8,
    power: 36,
    tier: 2,
    stealthLevel: 3,
    cooldown: 34,
    defenseBreak: 15,
    unlockLevel: 6,
  },
  {
    id: 'sql-safari',
    gameId: 'sql-safari',
    battleId: 19,
    name: 'SQL Safari',
    category: 'response',
    battleCategory: 'web',
    icon: 'Database',
    training: 'SQL Safety',
    strength: 'Recognizes unsafe query patterns and safer parameterized paths.',
    blindSpot: 'Needs web context to separate test input from attack traffic.',
    energy: 7,
    power: 35,
    tier: 2,
    stealthLevel: 3,
    cooldown: 32,
    defenseBreak: 16,
    unlockLevel: 6,
  },
  {
    id: 'stego-spy',
    gameId: 'stego-spy',
    battleId: 20,
    name: 'Stego Spy',
    category: 'sensor',
    battleCategory: 'advanced',
    icon: 'Eye',
    training: 'Hidden Data',
    strength: 'Finds hidden messages and suspicious embedded data.',
    blindSpot: 'Only helps when files or media are in scope.',
    energy: 7,
    power: 33,
    tier: 2,
    stealthLevel: 5,
    cooldown: 32,
    defenseBreak: 13,
    unlockLevel: 6,
  },
  {
    id: 'xss-xpert',
    gameId: 'xss-xpert',
    battleId: 21,
    name: 'XSS Xpert',
    category: 'response',
    battleCategory: 'web',
    icon: 'Code',
    training: 'Script Injection',
    strength: 'Finds unsafe rendering and explains safe output encoding.',
    blindSpot: 'Does not protect database or network layers.',
    energy: 7,
    power: 37,
    tier: 2,
    stealthLevel: 4,
    cooldown: 34,
    defenseBreak: 17,
    unlockLevel: 7,
  },
  {
    id: 'cert-champion',
    gameId: 'cert-champion',
    battleId: 22,
    name: 'Cert Champion',
    category: 'policy',
    battleCategory: 'crypto',
    icon: 'ShieldCheck',
    training: 'Certificate Safety',
    strength: 'Fixes certificate trust, expiry, and hostname mistakes.',
    blindSpot: 'Certificate health does not guarantee app safety.',
    energy: 7,
    power: 34,
    tier: 2,
    stealthLevel: 3,
    cooldown: 30,
    defenseBreak: 15,
    unlockLevel: 6,
  },
  {
    id: 'hash-hacker',
    gameId: 'hash-hacker',
    battleId: 23,
    name: 'Hash Hacker',
    category: 'response',
    battleCategory: 'crypto',
    icon: 'Fingerprint',
    training: 'Hash Matching',
    strength: 'Teaches hashes, integrity checks, and weak secret recovery.',
    blindSpot: 'Hash clues need account or file context.',
    energy: 8,
    power: 40,
    tier: 3,
    stealthLevel: 3,
    cooldown: 45,
    defenseBreak: 20,
    unlockLevel: 8,
  },
  {
    id: 'access-ace',
    gameId: 'access-ace',
    battleId: 24,
    name: 'Access Ace',
    category: 'policy',
    battleCategory: 'defense',
    icon: 'ShieldCheck',
    training: 'Least Privilege',
    strength: 'Narrows access to expected identities, services, and roles.',
    blindSpot: 'Can break dependencies without a map.',
    energy: 7,
    power: 38,
    tier: 3,
    stealthLevel: 4,
    cooldown: 42,
    defenseBreak: 18,
    unlockLevel: 8,
  },
  {
    id: 'log-analyzer',
    gameId: 'log-analyzer',
    battleId: 25,
    name: 'Log Analyzer',
    category: 'sensor',
    battleCategory: 'recon',
    icon: 'Activity',
    training: 'Incident Timeline',
    strength: 'Links symptoms to earlier events and proves sequence.',
    blindSpot: 'Needs a follow-up action to change system state.',
    energy: 6,
    power: 34,
    tier: 3,
    stealthLevel: 4,
    cooldown: 38,
    defenseBreak: 16,
    unlockLevel: 7,
  },
  {
    id: 'nmap-scanner',
    gameId: 'nmap-scanner',
    battleId: 26,
    name: 'Nmap Scanner',
    category: 'sensor',
    battleCategory: 'recon',
    icon: 'Search',
    training: 'Advanced Scanning',
    strength: 'Profiles hosts, ports, and services with stronger scan modes.',
    blindSpot: 'Loud scanning can trigger defensive cooldowns.',
    energy: 8,
    power: 42,
    tier: 3,
    stealthLevel: 2,
    cooldown: 50,
    defenseBreak: 22,
    unlockLevel: 9,
  },
  {
    id: 'dns-lookup-gui',
    gameId: 'dns-lookup-gui',
    battleId: 27,
    name: 'DNS Lookup GUI',
    category: 'sensor',
    battleCategory: 'network',
    icon: 'Globe',
    training: 'DNS Records',
    strength: 'Checks A, MX, TXT, and related records for useful clues.',
    blindSpot: 'Records can be stale or intentionally minimal.',
    energy: 5,
    power: 30,
    tier: 2,
    stealthLevel: 4,
    cooldown: 24,
    defenseBreak: 12,
    unlockLevel: 5,
  },
  {
    id: 'whois-lookup',
    gameId: 'whois-lookup',
    battleId: 28,
    name: 'Whois Lookup',
    category: 'sensor',
    battleCategory: 'recon',
    icon: 'Eye',
    training: 'Domain Ownership',
    strength: 'Surfaces registration, ownership, and timeline clues.',
    blindSpot: 'Privacy protection can hide useful details.',
    energy: 4,
    power: 28,
    tier: 2,
    stealthLevel: 5,
    cooldown: 22,
    defenseBreak: 10,
    unlockLevel: 5,
  },
  {
    id: 'sql-injector-gui',
    gameId: 'sql-injector-gui',
    battleId: 29,
    name: 'SQL Injector GUI',
    category: 'response',
    battleCategory: 'web',
    icon: 'Database',
    training: 'Injection Testing',
    strength: 'Demonstrates SQL injection safely in a contained lab.',
    blindSpot: 'Needs WAF or code fixes to become defense.',
    energy: 9,
    power: 50,
    tier: 3,
    stealthLevel: 2,
    cooldown: 60,
    defenseBreak: 25,
    unlockLevel: 10,
  },
  {
    id: 'xss-tester-gui',
    gameId: 'xss-tester-gui',
    battleId: 30,
    name: 'XSS Tester GUI',
    category: 'response',
    battleCategory: 'web',
    icon: 'Code',
    training: 'XSS Testing',
    strength: 'Tests reflected, stored, and DOM-style script risks safely.',
    blindSpot: 'Does not cover SQL or network exposure.',
    energy: 8,
    power: 46,
    tier: 3,
    stealthLevel: 4,
    cooldown: 54,
    defenseBreak: 23,
    unlockLevel: 9,
  },
  {
    id: 'hash-cracker-gui',
    gameId: 'hash-cracker-gui',
    battleId: 31,
    name: 'Hash Cracker GUI',
    category: 'response',
    battleCategory: 'crypto',
    icon: 'Fingerprint',
    training: 'Hash Cracking',
    strength: 'Shows why weak hashes and weak passwords fail.',
    blindSpot: 'Can be noisy and slow without good clues.',
    energy: 9,
    power: 48,
    tier: 3,
    stealthLevel: 2,
    cooldown: 58,
    defenseBreak: 24,
    unlockLevel: 10,
  },
  {
    id: 'phishing-sim-gui',
    gameId: 'phishing-sim-gui',
    battleId: 32,
    name: 'Phishing Sim GUI',
    category: 'special',
    battleCategory: 'social',
    icon: 'Mail',
    training: 'Social Simulation',
    strength: 'Models lure quality, credibility, and user-safety signals.',
    blindSpot: 'Should be paired with detection and education.',
    energy: 8,
    power: 44,
    tier: 3,
    stealthLevel: 5,
    cooldown: 52,
    defenseBreak: 20,
    unlockLevel: 9,
  },
  {
    id: 'cert-viewer-gui',
    gameId: 'cert-viewer-gui',
    battleId: 33,
    name: 'Cert Viewer GUI',
    category: 'sensor',
    battleCategory: 'crypto',
    icon: 'Eye',
    training: 'Certificate Inspection',
    strength: 'Inspects subject, issuer, expiry, and SAN fields quickly.',
    blindSpot: 'Inspection must be followed by policy change if broken.',
    energy: 5,
    power: 30,
    tier: 2,
    stealthLevel: 4,
    cooldown: 24,
    defenseBreak: 12,
    unlockLevel: 5,
  },
  {
    id: 'advanced-port-scan',
    gameId: 'advanced-port-scan',
    battleId: 34,
    name: 'Advanced Port Scan',
    category: 'sensor',
    battleCategory: 'recon',
    icon: 'Crosshair',
    training: 'Port Strategy',
    strength: 'Uses focused scan choices to profile exposed services.',
    blindSpot: 'Aggressive scans can be easy to detect.',
    energy: 8,
    power: 45,
    tier: 3,
    stealthLevel: 3,
    cooldown: 50,
    defenseBreak: 24,
    unlockLevel: 10,
  },
  {
    id: 'network-packet-tracer',
    gameId: 'network-packet-tracer',
    battleId: 35,
    name: 'Network Packet Tracer',
    category: 'map',
    battleCategory: 'network',
    icon: 'Activity',
    training: 'Packet Path Evidence',
    strength: 'Combines path view with packet evidence for network diagnosis.',
    blindSpot: 'Packet paths still need service-level context.',
    energy: 8,
    power: 43,
    tier: 3,
    stealthLevel: 3,
    cooldown: 46,
    defenseBreak: 21,
    unlockLevel: 9,
  },
  {
    id: 'xor-tool',
    gameId: 'xor-tool',
    battleId: 36,
    name: 'XOR Tool',
    category: 'special',
    battleCategory: 'crypto',
    icon: 'Code',
    training: 'XOR Encoding',
    strength: 'Reveals simple encoded strings and teaches reversible transforms.',
    blindSpot: 'Weak against modern encryption and unrelated traffic issues.',
    energy: 5,
    power: 32,
    tier: 2,
    stealthLevel: 4,
    cooldown: 26,
    defenseBreak: 13,
    unlockLevel: 6,
  },
  {
    id: 'trojan-builder',
    gameId: 'trojan-builder',
    battleId: 37,
    name: 'Trojan Builder',
    category: 'response',
    battleCategory: 'malware',
    icon: 'Bug',
    training: 'Malware Anatomy',
    strength: 'Explains how trojan behavior is staged and detected safely.',
    blindSpot: 'Needs strict containment and detection context.',
    energy: 10,
    power: 55,
    tier: 3,
    stealthLevel: 5,
    cooldown: 70,
    defenseBreak: 28,
    unlockLevel: 12,
  },
  {
    id: 'keylogger-sim',
    gameId: 'keylogger-sim',
    battleId: 38,
    name: 'Keylogger Sim',
    category: 'special',
    battleCategory: 'malware',
    icon: 'Fingerprint',
    training: 'Input Capture Awareness',
    strength: 'Teaches keylogging risks and detection in a safe simulation.',
    blindSpot: 'Must be paired with endpoint and access controls.',
    energy: 10,
    power: 52,
    tier: 3,
    stealthLevel: 5,
    cooldown: 68,
    defenseBreak: 26,
    unlockLevel: 12,
  },
];

export const DEFAULT_DUEL_LOADOUT: Record<SimuleToolCategory, string> = {
  map: 'network-navigator',
  sensor: 'dns-resolver',
  policy: 'firewall-defender',
  response: 'malware-hunter',
  recovery: 'load-balancer',
  special: 'cyber-duel-arena',
};

export function getSimuleToolById(id: string): SimuleTool {
  return SIMULE_TOOLS.find((tool) => tool.id === id || tool.gameId === id) ?? SIMULE_TOOLS[0];
}

export function getSimuleToolsByIds(ids: readonly string[]): SimuleTool[] {
  return ids.map(getSimuleToolById);
}
